### PR TITLE
rds: fix value copy operation of tags and process features

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

The iteration overrides the same pointer's value. I have encountered this bug during the first implementation of tags and fixed but I don't know how the change got lost :(

Manually tested, it's working.

@jbw976 I think we'll need to do a patch release of AWS provider. Since we tag the resources with default tags, RDS is unusable without this fix. I opened this PR against `release-0.7` because `master` contains some breaking changes like IAMRole being `v1beta1`, so, the patch release should only include this commit.

Fixes https://github.com/crossplane/stack-minimal-aws/issues/12

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the dependencies in [`app.yaml`] to include any new role permissions.

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplane/crossplane/tree/master/PendingReleaseNotes.md
[`app.yaml`]: https://github.com/crossplane/provider-aws/blob/master/config/stack/manifests/app.yaml

### CODE REVIEW

**Comment by muvaf** [comment]
> @muvaf we can still cherry-pick only the commit in #179 to release-0.7 and it shouldn't cause any issues related to IAM role updates.

@hasheddan If I understood you correctly, that's what this PR does. Two PRs have the same commit but this one is against `release-0.7` and the other one is against `master`.

**Comment by hasheddan** [comment]
@muvaf it is typically best practice to commit to master then git cherry-pick -x to the release branch

**Comment by muvaf** [comment]
@hasheddan oh do you mean the cherry-pick should be done _after_ the commit is merged to master? That makes sense.

**Comment by hasheddan** [comment]
@muvaf yep! Or at least just be explicitly cherry-picked from the `master` commit (i.e. `-x`), which it looks like you force pushed and updated :) Thanks again for fixing this!

**Pull request merged**
