### PR TITLE
Cloudfront Function resource

### LINKED ISSUE #1215: Cloudfront Function Resource
### What problem are you facing?

After trying to attach a Lambda function to Cloudfront as a Cloudfront function, I realized Lambda and Cloudfront functions have nothing to do with each other. Cloudfront Functions are a totally new resource and they fall under the cloudfront api. These are not something I can create with Crossplane at the moment. 

### How could Crossplane help solve your problem?

Make a new Cloudfront Function resource like so:

```yaml
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: rewriter
spec:
  forProvider:
    comment:  A lil rewriter
    runtime: cloudfront-js-1.0
    code: |
      function handler(event) {
          var request = event.request;
          if (!/\..+/.test(request.uri)) {
              request.uri = `/index.html`;
          }
          return request;
      }
```

### PR DESCRIPTION
**Pull request by kferrone**
I removed the Function from ignored list and  initialized setup.go

### Description of your changes

Followed the guide for generating resources so I can make a Cloudfront Function resource. 

Fixes #1215 

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by kferrone** [comment]
I got it started I think. I'm totally new to Go and I'm usually super busy. I hope this can be enough for someone to take it to the finish line. 

I'm also on Mac M1 Arm64 so I can't quite build the way the docs said. 

I'v tried these commands but they don't work anymore after what I did

```
make -j4
make services SERVICES=cloudfront
```

Also the CRD did not actually generate??

And this command is scary and changed lots of files, so I reverted all that it did. 
```
make generate
```

**Comment by haarchri** [comment]
@kferrone thanks for opening the PR - i also using M1 Mac without issues

make submodules
make generate ( if successful the generator generate and Check all CRDs/resources for updates) 

check If you using latest master
check If you using go1.17

**Comment by kferrone** [comment]
I have this GO version:
```
go version go1.17.3 darwin/arm64
```
Is this OK? 

I get this error when running the `make generate`

```
HEAD is now at f8c0f47 Use `SetConfig` in `SetResourceForStruct` when target shape has no members (#292)
15:03:54 [ .. ] Generating kinesis controllers and CRDs
15:04:05 [ OK ] Generating kinesis controllers and CRDs
15:04:05 [ .. ] Generating secretsmanager controllers and CRDs
15:04:10 [ OK ] Generating secretsmanager controllers and CRDs
15:04:10 [ .. ] Generating kms controllers and CRDs
15:04:15 [ OK ] Generating kms controllers and CRDs
15:04:15 [ .. ] Generating glue controllers and CRDs
15:04:19 [ OK ] Generating glue controllers and CRDs
15:04:19 [ .. ] Generating prometheusservice controllers and CRDs
15:04:22 [ OK ] Generating prometheusservice controllers and CRDs
15:04:22 [ .. ] Generating cloudfront controllers and CRDs
Error: cannot run goimports: exit status 2
exit status 1
make[2]: *** [services] Error 1
make[1]: *** [services.all] Error 2
make: *** [generate] Error 2
```

What am I doing that is causing so many updates when I run that command though?

**Comment by kferrone** [comment]
There are conflicts when I generate the code. 

Within this file: https://github.com/crossplane/provider-aws/blob/master/apis/cloudfront/v1alpha1/zz_types.go
There are already structs named Function and FunctionList which are part of the FunctionAssociations within the Distributions. So basically, functionAssociations bites me again.

Can I add a prefix to the resource so it is named CloudfrontFunction? Is there a better way to deal with this situation? I would actually prefer keeping the original name of Function.

**Comment by kferrone** [comment]
I totally bungled the branch. I made new one based on updated master. I did nothing different than before, it works now. So something happened on master which made this work. I'll close this PR and make a new one with working code.

**Pull request closed without merging**
