### PR TITLE
Implement athena workgroup

### LINKED ISSUE #523: Implement Amazon Athena service
### What problem are you facing?
Amazon Athena resources are missing.

https://docs.aws.amazon.com/sdk-for-go/api/service/athena/

### How could Crossplane help solve your problem?
Use ACK to generate athena service and then fill the gaps.

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: Christopher Haar <chhaar30@googlemail.com>

### Description of your changes

added athena object:
- WorkGroup

Fixes  #523

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

```
k get workgroup.athena.aws.crossplane.io/crossplane-workgroup
NAME                                                      READY   SYNCED   EXTERNAL-NAME
workgroup.athena.aws.crossplane.io/crossplane-workgroup   True    True     crossplane-workgroup
```

```
k describe workgroup.athena.aws.crossplane.io/crossplane-workgroup
Name:         crossplane-workgroup
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: crossplane-workgroup
API Version:  athena.aws.crossplane.io/v1alpha1
Kind:         WorkGroup
Metadata:
  Creation Timestamp:  2021-06-25T19:18:36Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        2
  Resource Version:  837083
  Self Link:         /apis/athena.aws.crossplane.io/v1alpha1/workgroups/crossplane-workgroup
  UID:               ee6cdc93-c62a-4fa1-be00-e4e3ebedcd8c
Spec:
  Deletion Policy:  Delete
  For Provider:
    Configuration:
      Enforce Work Group Configuration:  true
      Engine Version:
        Effective Engine Version:           Athena engine version 2
        Selected Engine Version:            AUTO
      Publish Cloud Watch Metrics Enabled:  true
      Requester Pays Enabled:               false
    Description:                            crossplane-workgroup
    Region:                                 eu-central-1
    Tags:
      Key:    key
      Value:  value
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2021-06-25T19:18:37Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2021-06-25T19:18:37Z
    Reason:                Available
    Status:                True
    Type:                  Ready
Events:                    <none>
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by AaronME** [comment]
@haarchri Please rebase on master and we can run this through testing.

Thank you!

**Comment by haarchri** [comment]
@AaronME rebased and tested again 

```
 kubectl describe workgroup.athena.aws.crossplane.io/example
Name:         example
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: example
API Version:  athena.aws.crossplane.io/v1alpha1
Kind:         WorkGroup
Metadata:
  Creation Timestamp:  2021-09-24T17:30:26Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        2
  Resource Version:  5016880
  Self Link:         /apis/athena.aws.crossplane.io/v1alpha1/workgroups/example
  UID:               1327bffc-fef6-4fe7-bdd8-8d8e753ae1ee
Spec:
  Deletion Policy:  Delete
  For Provider:
    Configuration:
      Enforce Work Group Configuration:  true
      Engine Version:
        Effective Engine Version:           Athena engine version 2
        Selected Engine Version:            AUTO
      Publish Cloud Watch Metrics Enabled:  true
      Requester Pays Enabled:               false
    Description:                            example
    Region:                                 us-east-1
    Tags:
      Key:    key
      Value:  value
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2021-09-24T17:30:27Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2021-09-24T17:30:27Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age   From                                        Message
  ----    ------                   ----  ----                                        -------
  Normal  CreatedExternalResource  24s   managed/workgroup.athena.aws.crossplane.io  Successfully requested creation of external resource

```

**Comment by haarchri** [comment]
i will squash commits and rerun make generate for latest update

**Comment by haarchri** [comment]
done ready for review

**Comment by haarchri** [comment]
@AaronME rebased and changed ratelimiter + rerun generation

**Comment by haarchri** [comment]
rebase done

**Review by AaronME — APPROVED** [review]
LGTM! Thank you, @haarchri !

**Pull request merged**
