### PR TITLE
Improve Cloudfront Configuration

### LINKED ISSUE #1108: Improve experience of configuring cloudfront distributions
### What happened?
Configuring cloudfront distribution seems to be a bit buggy. Some fields that are under `defaultCacheBehavior` are not required but once I introduced `cacheBehaviors `section then suddenly almost all fields become required and specifying `quantity` does not help on the experience.

Another issue is that the resource never goes into Ready state:
```
NAME                         READY   SYNCED   EXTERNAL-NAME
somedomain                   False   True     E1U92C17PI1M42
```
It seems like the provider has entered an infinite loop with reconciling the updates to the resource. This is maybe related to this issue https://github.com/crossplane/provider-aws/issues/894

### How can we reproduce it?
Here is the distribution that I was testing:

```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: somedomain
spec:
  providerConfigRef:
    name: my-namespace-aws
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution 3
      priceClass: PriceClass_100
      origins:
        items:
          - domainName: app.my.cloud
            id: customOrigin
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "https-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1.2
                quantity: 1
      cacheBehaviors:
        quantity: 1
        items:
        - pathPattern: /*/services-email-validation-api/*          
          smoothStreaming: false # Why is it required??
          targetOriginID: customOrigin
          compress: false
          viewerProtocolPolicy: https-only
          allowedMethods:        
            cachedMethods: # Why is it required??
              items:
              - HEAD
              - GET
              quantity: 2
            items:
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
            quantity: 7
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          fieldLevelEncryptionID: "" # Why is this required ?
          forwardedValues:
            queryString: true 
            queryStringCacheKeys:  # Why is this required ?
              quantity: 0          # Why is this required ?              
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
              quantity: 8  
          lambdaFunctionAssociations: # Why is this required ?
            quantity: 0
      defaultCacheBehavior:
        targetOriginID: customOrigin
        compress: false
        viewerProtocolPolicy: https-only
        allowedMethods:
          cachedMethods: # is not required before adding cacheBehaviors section!
            items:
            - HEAD
            - GET        
            quantity: 2            
          items:
          - GET 
          - HEAD 
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
          quantity: 7
        minTTL: 0
        maxTTL: 0
        defaultTTL: 0
        forwardedValues:
          queryString: true
          cookies:
            forward: all
          headers:
            items:
            - Accept
            - Accept-Charset
            - Accept-Encoding
            - Accept-Language
            - Authorization
            - Accept-Datetime
            - Referer
            - Origin
            quantity: 8
        lambdaFunctionAssociations: # is not required before adding cacheBehaviors section!
          quantity: 0
```

### PR DESCRIPTION
**Pull request by ezgidemirel**
### Description of your changes
In this change, we are:
- solving infinite update loop issue
- late initializing the elements of "Items" array
- deducing "quantity" field from length of the "Items" array

Please note that, this change causes API changes. It removes `quantity` fields from the CRD.

Fixes #1108 #789 #1174 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- Created a Cloudfront distribution with the following manifest:
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: ezgi
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution 3
      priceClass: PriceClass_100 
      origins:
        items:
          - domainName: app.my.cloud
            id: customOrigin
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "https-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1.2
      cacheBehaviors:
        items:
        - pathPattern: /*/services-email-validation-api/*          
          targetOriginID: customOrigin
          compress: false
          viewerProtocolPolicy: https-only
          allowedMethods:        
            items: 
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          forwardedValues:
            queryString: true         
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
      defaultCacheBehavior:
        targetOriginID: customOrigin
        compress: false
        viewerProtocolPolicy: https-only
        allowedMethods:    
          items:
          - GET 
          - HEAD 
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        minTTL: 0
        maxTTL: 0
        defaultTTL: 0
        forwardedValues:
          queryString: true
          cookies:
            forward: all
          headers:
            items:
            - Accept
            - Accept-Charset
            - Accept-Encoding
            - Accept-Language
            - Authorization
            - Accept-Datetime
            - Referer
            - Origin
```
- Updated `spec.forProvider.distributionConfig.cacheBehaviors.items[0].allowedMethods.cachedMethods` as below:
```
ky distribution.cloudfront.aws.crossplane.io/ezgi -o jsonpath='{.spec.forProvider.distributionConfig.cacheBehaviors.items[0].allowedMethods.cachedMethods}'
{"items":["HEAD","GET"]}
```
```
kubectl get managed                                                                Ezgis-MacBook-Pro.local: Wed Mar  2 15:46:54 2022

Warning: Please use v1beta1 version of SNS group.
NAME                                             READY   SYNCED   EXTERNAL-NAME
distribution.cloudfront.aws.crossplane.io/ezgi   True    True     E3B8N1APYMYPBX

NAME                                      READY   SYNCED   AGE
bucket.s3.aws.crossplane.io/ezgi-bucket   True    True     7d22h
```

- Deleted the resource

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
@ezgidemirel thanks for this enhancement - does this also fixes https://github.com/crossplane/provider-aws/issues/1174 ?

**Review by haarchri — APPROVED** [review]
LGTM - tested the implementation with the following issues: #1108 #789 and #1174

**Comment by SAEb-ai** [comment]
Hi @muvaf!! I am interested in applying for **Report breaking changes in CRD schemas for Pull Requests** project of Crosspalne under the summer cohort of LFX mentorship program, 2022. 

It took a lot out of me to come to [those PR's](https://github.com/crossplane/provider-aws/issues?q=label%3Abreaking-change+is%3Aclosed) that were labelled as `breaking-change` to understand what changes are actually considered as breaking. Here are a few thoughts that had came to my mind after seeing some discussions in the PR's that are marked as breaking-change:

- When there is a change in `group` of spec in CRD (https://github.com/crossplane/provider-aws/pull/446#issuecomment-732298686), consider that change to be breaking.
- When there is change in a field in openAPIV3Schema i.e when a particular field is deleted or the type and format of the particular field are changed( [File](https://github.com/crossplane/provider-aws/pull/1186/files#diff-b04d7639b160d2b3024f5ea75b1009dd6b7d99af23148d252507395ea3d0e6cf)), consider that change to be breaking.

I just wanted to confirm from you whether my understanding of the project related to breaking changes is going in the right direction or not? Also, it would be really helpful for me in understanding the project more thoroughly if you could please state some more points that the whole community considers for breaking-changes.

**Comment by muvaf** [comment]
Hi @SAEb-ai ! I'd like to reiterate what I mentioned [in the issue,](https://github.com/crossplane/crossplane/issues/2863#issuecomment-1123536284) please do not start any work/design before acceptance since we reserved that issue to the selected mentee, so your work may end up being not merged.

Regarding your findings, yes these are considered as breaking changes. You can also look up what's considered as breaking change in OpenAPI format as that's a widely accepted standard.

**Comment by SAEb-ai** [comment]
> Hi @SAEb-ai ! I'd like to reiterate what I mentioned https://github.com/crossplane/crossplane/issues/2863#issuecomment-1123536284 please do not start any work/design before acceptance since we reserved that issue to the selected mentee, so your work may end up being not merged.

Yep. I have seen that. But I am not preparing any design doc. I am just trying to understand the project thoroughly which in turn would help me in writing the cover letter in a more verbose way.

> Regarding your findings, yes these are considered as breaking changes. You can also look up what's considered as breaking change in OpenAPI format as that's a widely accepted standard.

Thanks @muvaf for specifying more pointers. I got my answer.

**Pull request merged**
