### PR TITLE
Add ECR LifecyclePolicy with codegen

### LINKED ISSUE #864: LifecyclePolicy For ECR Repositories
### What problem are you facing?
We are using crossplane to create ECR Repositories for CICD pipelines, but while we are able to create the repositories, we are unable to add a lifecycle policy to the specific repository through crossplane.

> A lifecycle policy contains one or more rules, where each rule defines an action for Amazon ECR. This provides a way to automate the cleaning up of unused images, for example expiring images based on age or count

### How could Crossplane help solve your problem?
We would like a way of applying Lifecycle policies to ECR repositories.

Input object (a string of the json policy rules): https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr#PutLifecyclePolicyInput
Rule syntax: https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html#lifecycle_policy_syntax

### PR DESCRIPTION
**Pull request by larhauga**
### Description of your changes
Add new LifecyclePolicy for ECR Repositories

Fixes #864
Replaces #870

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Tested with example resources against local kind cluster.

[contribution process]: https://git.io/fj2m9
ecr-lifecyclepolicy

### CODE REVIEW

**Review by haarchri — APPROVED** [review]
thanks for implementation - i handled the create, update & delete 

```
NAME                                       READY   SYNCED   ID        URI
repository.ecr.aws.crossplane.io/example   True    True     example   xxx.dkr.ecr.us-east-1.amazonaws.com/example

NAME                                            READY   SYNCED   EXTERNAL-NAME
lifecyclepolicy.ecr.aws.crossplane.io/example   True    True     example
```

i will add rebase & adoption to latest runtime changes with a commit

**Comment by haarchri** [comment]
have no access rights for pushing the rebase :/

```
git push git@github.com:sparebank1utvikling/provider-aws.git --force
ERROR: Permission to sparebank1utvikling/provider-aws.git denied to haarchri.
```

**Comment by chlunde** [comment]
@haarchri thanks! force-pushed to [f028629](https://github.com/crossplane/provider-aws/commit/f02862969a57a72c38930dfdbdd68384329deda9) now

**Review by haarchri — APPROVED** [review]
@chlunde  thanks for force push ;)

**Pull request merged**
