### PR TITLE
DynamoDB services are generated by ACK

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

3 available (`Backup`, `Table` and `GlobalTable`) DynamoDB services are generated by ACK. We already had `DynamoTable` CRD. I removed it since `Table` replaces it and copied over all the additional functionality like update that is not available in ACK yet to `Table` hooks.

Fixes https://github.com/crossplane/provider-aws/issues/447

TODO:
* [x] Examples

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually with added examples.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by muvaf** [comment]
This should be ready to go.

**Comment by muvaf** [comment]
Marked as breaking-change since we remove `apiVersion: database.aws.crossplane.io kind: DynamoTable` CRD in favor of `apiVersion: dynamodb.aws.crossplane.io kind: Table`

**Review by krishchow — COMMENTED** [review]
This all LGTM, just one question - I wasn't able to see any unit-tests listed for the Backup, Table or GlobalTable. Is this the expected behavior for the generated controllers?

**Comment by muvaf** [comment]
@krishchow Thanks for the review. I migrated the existing tests of DynamoDB Table (to `hooks_test.go`) but I don't think we need tests for the generated parts. What do you think?

**Review by krishchow — APPROVED** [review]
@muvaf that sounds good. Out of curiosity, if there are any updates to AWS or ACK, will the code generation need to be run again in full?

**Comment by muvaf** [comment]
@krishchow yes, I believe at one point we'll make the code generation part of CI/CD, probably to be run as part of `make generate`. I'm planning a revision in `hooks.go` files where we'd supply only the functions we customize, as opposed to getting a boilerplate and editing that file.

**Pull request merged**
