### PR TITLE
feat(vpcendpointserviceconfiguration) added new ressource

### LINKED ISSUE #956: Request for VPC endpoint service
### What resource do you need?

We need to create [VPC endpoint service](https://docs.aws.amazon.com/vpc/latest/privatelink/endpoint-service.html).

### What is your use case?

We're SaaS vendor, and part of our job is to do LCM for AWS infra. We don't want to expose our service to the public internet, and we want to expose the service to a tenant securely via private link. It would be ideal if we have VPC endpoint service CRD so we can use k8s as a framework to manage the infra LCM.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
I think so. My team has a fork of crossplane and we would be willing to contribute once we're done on our side. The main support we need is to get early feedback/insights from upstream and make decisions on the VPC endpoint service schema. Once that is done, we can consume our fork without worrying about the future divergence.

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

### Description of your changes

Fixes #956 https://github.com/crossplane/provider-aws/issues/1046
- implemented resource vpcendpointserviceconfiguration & referencers/resolver
- fixed one problem that LoadBalancerType is not set https://github.com/crossplane/provider-aws/pull/865 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- create
- update
- delete
```
kubectl describe vpcendpointserviceconfiguration.ec2.aws.crossplane.io/sample-vpc-endpoint-service 
Name:         sample-vpc-endpoint-service
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2021-12-31T13:36:36+01:00
              crossplane.io/external-create-succeeded: 2021-12-31T13:36:36+01:00
              crossplane.io/external-name: vpce-svc-0903dc23c756410ad
API Version:  ec2.aws.crossplane.io/v1alpha1
Kind:         VPCEndpointServiceConfiguration
Metadata:
  Creation Timestamp:  2021-12-31T12:36:35Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  4
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:gatewayLoadBalancerARNRefs:
          f:region:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-12-31T12:36:35Z
    API Version:  ec2.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:acceptanceRequired:
          f:gatewayLoadBalancerARNs:
          f:tagSpecifications:
      f:status:
        .:
        f:atProvider:
          .:
          f:serviceConfiguration:
            .:
            f:availabilityZones:
            f:gatewayLoadBalancerARNs:
            f:managesVPCEndpoints:
            f:serviceID:
            f:serviceName:
            f:serviceState:
        f:conditions:
    Manager:         provider
    Operation:       Update
    Time:            2021-12-31T12:36:36Z
  Resource Version:  2674064
  UID:               dc9f5928-dbbb-45b3-a135-17a7166632fd
Spec:
  Deletion Policy:  Delete
  For Provider:
    Acceptance Required:  true
    Gateway Load Balancer ARN Refs:
      Name:  gatewayloadbalancer
    Gateway Load Balancer AR Ns:
      arn:aws:elasticloadbalancing:us-east-1:255932642927:loadbalancer/gwy/gatewayloadbalancer/76d29132bba8c949
    Region:  us-east-1
    Tag Specifications:
      Resource Type:  vpc-endpoint-service
      Tags:
        Key:    Name
        Value:  sample-vpc-endpoint-service
        Key:    crossplane-kind
        Value:  vpcendpointserviceconfiguration.ec2.aws.crossplane.io
        Key:    crossplane-name
        Value:  sample-vpc-endpoint-service
        Key:    crossplane-providerconfig
        Value:  example
  Provider Config Ref:
    Name:  example
Status:
  At Provider:
    Service Configuration:
      Availability Zones:
        us-east-1b
        us-east-1c
      Gateway Load Balancer AR Ns:
        arn:aws:elasticloadbalancing:us-east-1:255932642927:loadbalancer/gwy/gatewayloadbalancer/76d29132bba8c949
      Manages VPC Endpoints:  false
      Service ID:             vpce-svc-0903dc23c756410ad
      Service Name:           com.amazonaws.vpce.us-east-1.vpce-svc-0903dc23c756410ad
      Service State:          Available
  Conditions:
    Last Transition Time:  2021-12-31T12:36:37Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2021-12-31T12:36:36Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by hanlins** [comment]
Hi @haarchri, I'm trying to consume the vpc endpoint service object's ARN in the `.status.atProvider` field, but it's empty. Can you fill that, I'm expecting to get something similar to EKS:
```yaml
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  annotations:
    crossplane.io/external-create-pending: "2021-12-29T15:06:18-08:00"
    crossplane.io/external-create-succeeded: "2021-12-29T15:06:19-08:00"
    crossplane.io/external-name: eks-1228
    kubectl.kubernetes.io/last-applied-configuration: |
xxxx
  creationTimestamp: "2021-12-29T23:06:17Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: eks-1228
  resourceVersion: "7004"
  uid: 4590ef90-5f7f-45cc-b478-b2bfa91b6e09
spec:
  deletionPolicy: Delete
  forProvider:
    logging:
      clusterLogging:
      - enabled: false
        types:
        - api
        - audit
        - authenticator
        - controllerManager
        - scheduler
    region: us-west-2
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: false
      securityGroupIds:
      - sg-0aaf6c7acee5950d6
      subnetIds:
      - subnet-0a5f5caaa1187bf34
      - subnet-0c3c27f8467f57f5b
      - subnet-04f8da94dcb87f2c0
    roleArn: arn:aws:iam::510387698298:role/eks-role-hl-1228
    tags:
      Vendor: PingCAP
      crossplane-kind: cluster.eks.aws.crossplane.io
      crossplane-name: eks-1228
      crossplane-providerconfig: tidbcloud-hl-demo-1228
    version: "1.21"
  providerConfigRef:
    name: tidbcloud-hl-demo-1228
status:
  atProvider:
    arn: arn:aws:eks:us-west-2:510387698298:cluster/eks-1228
    createdAt: "2021-12-29T23:06:19Z"
    endpoint: https://xxxxxx.sk1.us-west-2.eks.amazonaws.com
    identity:
      oidc:
        issuer: https://oidc.eks.us-west-2.amazonaws.com/id/xxxxxx
    platformVersion: eks.4
    resourcesVpcConfig:
      clusterSecurityGroupId: sg-0136119044af76546
      vpcId: vpc-0e024f216418e1235
    status: ACTIVE
  conditions:
  - lastTransitionTime: "2021-12-29T23:19:30Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-12-29T23:06:20Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
In eks object above, I can retrieve the ARN under the `atProvider` field. I'm expecting that I can get vpcendpointservice's ARN under this field. Thanks!

**Comment by haarchri** [comment]
@hanlins looks like that we have no field for the ARN in status.atProvider - did we have the ARN in aws cli when we describe ?

**Comment by hanlins** [comment]
> @hanlins looks like that we have no field for the ARN in status.atProvider - did we have the ARN in aws cli when we describe ?

Hi @haarchri, I see, that's true, the ARN doesn't exist. I'm wondering is it possible to put an identifier like the `ServiceName` in the status? Take an example, here's the output for my ep service:
```json
        {
            "ServiceName": "com.amazonaws.vpce.us-west-2.vpce-svc-xxx",
            "ServiceId": "vpce-svc-xxxxxx",
            "ServiceType": [
                {
                    "ServiceType": "Interface"
                }
            ],
            "AvailabilityZones": [
                "us-west-2a",
                "us-west-2b"
            ],
            "Owner": "xxxxx",
            "BaseEndpointDnsNames": [
                "vpce-svc-xxxxx.us-west-2.vpce.amazonaws.com"
            ],
            "VpcEndpointPolicySupported": false,
            "AcceptanceRequired": true,
            "ManagesVpcEndpoints": false,
            "Tags": [
                {
                    "Key": "crossplane-providerconfig",
                    "Value": "default"
                },
                {
                    "Key": "crossplane-kind",
                    "Value": "vpcendpointserviceconfiguration.ec2.aws.crossplane.io"
                },
                {
                    "Key": "crossplane-name",
                    "Value": "res-test1-us-west-2-eks-1228-frps-endpoint-svc"
                },
                {
                    "Key": "Name",
                    "Value": "res-test1-us-west-2-eks-1228-frps-endpoint-svc"
                }
            ]
        }
```
It would be ideal if I can get the service name `com.amazonaws.vpce.us-west-2.vpce-svc-xxx` from the object's status, then I don't need to send another request to AWS to retrieve the service name. I'm trying to build a private link, that requires the service name of a vpc endpoint service as an input parameter for a vpc endpoint object, so it would be ideal to have the service name in the output :)

**Comment by hanlins** [comment]
Another demand is, we want to automatically approve the private link from certain principals, for now, we can't specify the principals in the vpcendpointservice object, and we have add some certain principal using following command:
```
aws ec2 modify-vpc-endpoint-service-permissions --service-id vpce-svc-xxx --add-allowed-principals arn:aws:iam::xxx:root
```
It would be nice if we can directly specify the principal on the vpc ep svc CR. Since there's no options in `create-vpc-endpoint-service-configuration` command to specify the allowed principal, maybe we can create a separate issue to track that after this changeset got merged. Thanks!

**Comment by haarchri** [comment]
yeah i'am aware of this second resource - think the best is - to have a seperate resource like vpc-endpointservice-configuration-allowed-principals

 
```
 ​ModifyVpcEndpointServicePermissions​
&​ec2.​ModifyVpcEndpointServicePermissionsInput​
```

**Comment by hanlins** [comment]
> yeah i'am aware of this second resource - think the best is - to have a seperate resource like vpc-endpointservice-configuration-allowed-principals
> 
> ```
>  ​ModifyVpcEndpointServicePermissions​
> &​ec2.​ModifyVpcEndpointServicePermissionsInput​
> ```

That will be great!

**Comment by haarchri** [comment]
@hanlins added fileds for `atProvider`

```
Status:
  At Provider:
    Service Configuration:
      Availability Zones:
        us-east-1b
        us-east-1c
      Gateway Load Balancer AR Ns:
        arn:aws:elasticloadbalancing:us-east-1:255932642927:loadbalancer/gwy/gatewayloadbalancer/76d29132bba8c949
      Manages VPC Endpoints:  false
      Service ID:             vpce-svc-0903dc23c756410ad
      Service Name:           com.amazonaws.vpce.us-east-1.vpce-svc-0903dc23c756410ad
      Service State:          Available
```

**Comment by haarchri** [comment]
@AaronME  rebased & tested again

**Review by AaronME — APPROVED** [review]
LGTM!

**Pull request merged**
