### PR TITLE
Fix missing region in all resources

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

Adds region field, does some fixes for CRDs and updates the examples. Note that `region` field is kept optional in `beta` resources. So, people who use `providerRef` will not be broken in this version.

I'm trying to test each and every resource and plan to do a revamp of the examples folder(fix many of them, add missing ones) which will include removal of all claim/class CRs. I want that folder to work with `kubectl apply -f` so maybe in the future we can have some kind of integration test for them.

Fixes https://github.com/crossplane/provider-aws/issues/336

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the dependencies in [`app.yaml`] to include any new role permissions.

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplane/crossplane/tree/master/PendingReleaseNotes.md
[`app.yaml`]: https://github.com/crossplane/provider-aws/blob/master/config/package/manifests/app.yaml

### CODE REVIEW

**Comment by muvaf** [comment]
It's all well and working now. I had to test each and every managed resource we have and do fixes :( `examples` folder is now accurate and we have an example for all managed resources.

**Review by hasheddan — COMMENTED** [review]
Thanks for tackling this @muvaf! Mostly looks good to me with a few small comments :) Feel free to ping me for approval after fixes 👍

**Comment by muvaf** [comment]
@hasheddan Thanks for the review! Addressed all of your comments.

**Review by hasheddan — APPROVED** [review]
Awesome! Thanks again @muvaf :)

**Comment by kasey** [comment]
Adding some metadata: this PR is a fix for a breaking change introduced in https://github.com/crossplane/provider-aws/pull/320 which addressed https://github.com/crossplane/provider-aws/issues/38

**Pull request merged**
