### PR TITLE
fix: add missing region field for providerconfig v1beta1

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <git@frezbo.com>

### Description of your changes
add missing region field for providerconfig v1beta1

FIxes:

```bash
2020-09-10T16:02:42.981+0530	DEBUG	provider-aws	Cannot create external resource	{"controller": "managed/vpc.ec2.aws.crossplane.io", "request": "/frezbo-vpc", "uid": "1c03a87b-de4c-40d6-a9aa-8e0ddab5b29b", "version": "1363", "external-name": "", "error": "failed to create the VPC resource: unknown endpoint, could not resolve endpoint, partition: \"aws\", service: \"ec2\", region: \"\", known: [ap-northeast-2 ap-southeast-1 fips-us-west-1 us-east-1 ap-northeast-1 ap-southeast-2 ca-central-1 eu-south-1 eu-west-2 eu-west-3 fips-us-west-2 af-south-1 ap-south-1 eu-central-1 eu-north-1 fips-us-east-2 ap-east-1 eu-west-1 fips-ca-central-1 fips-us-east-1 me-south-1 sa-east-1 us-east-2 us-west-1 us-west-2]", "errorVerbose": "unknown endpoint, could not resolve endpoint, partition: \"aws\", service: \"ec2\", region: \"\", known: [ap-northeast-2 ap-southeast-1 fips-us-west-1 us-east-1 ap-northeast-1 ap-southeast-2 ca-central-1 eu-south-1 eu-west-2 eu-west-3 fips-us-west-2 af-south-1 ap-south-1 eu-central-1 eu-north-1 fips-us-east-2 ap-east-1 eu-west-1 fips-ca-central-1 fips-us-east-1 me-south-1 sa-east-1 us-east-2 us-west-1 us-west-2]\nfailed to create the VPC resource\ngithub.com/crossplane/provider-aws/pkg/controller/ec2/vpc.(*external).Create\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/pkg/controller/ec2/vpc/controller.go:181\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.9.1-0.20200827134951-29150890d4c1/pkg/reconciler/managed/reconciler.go:620\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/ngeorgi/work/golang/src/github.com/crossplane/provider-aws/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/Cellar/go/1.15.1/libexec/src/runtime/asm_amd64.s:1374", "requeue-after": "2020-09-10T16:03:12.981+0530"}
2020-09-10T16:02:42.982+0530	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"VPC","name":"frezbo-vpc","uid":"1c03a87b-de4c-40d6-a9aa-8e0ddab5b29b","apiVersion":"ec2.aws.crossplane.io/v1beta1","resourceVersion":"1385"}, "reason": "CannotCreateExternalResource", "message": "failed to create the VPC resource: unknown endpoint, could not resolve endpoint, partition: \"aws\", service: \"ec2\", region: \"\", known: [ap-northeast-2 ap-southeast-1 fips-us-west-1 us-east-1 ap-northeast-1 ap-southeast-2 ca-central-1 eu-south-1 eu-west-2 eu-west-3 fips-us-west-2 af-south-1 ap-south-1 eu-central-1 eu-north-1 fips-us-east-2 ap-east-1 eu-west-1 fips-ca-central-1 fips-us-east-1 me-south-1 sa-east-1 us-east-2 us-west-1 us-west-2]"}
2020-09-10T16:02:42.991+0530	DEBUG	provider-aws	Reconciling	{"controller": "managed/vpc.ec2.aws.crossplane.io", "request": "/frezbo-vpc"}
```

I have:
- [ x ] Run `make reviewable` to ensure this PR is ready for review.
- [ x ] Ensured this PR contains a neat, self documenting set of commits.
- [ x ] Updated any relevant [documentation], [examples], or [release notes].
- [ x ] Updated the dependencies in [`app.yaml`] to include any new role permissions.

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@frezbo this is actually intentional, more info here: https://github.com/crossplane/provider-aws/issues/38

**Comment by frezbo** [comment]
@hasheddan ok that makes sense not to have region in `providerConfig` but passing the `region` is secret won't work as it's never parsed. I'm getting the endpoint error without this change.

**Comment by frezbo** [comment]
This is my YAML spec:

```yaml
---
apiVersion: v1
data:
  credentials: <redacted>
kind: Secret
metadata:
  name: aws-account-creds
  namespace: crossplane-system
type: Opaque
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
spec:
  region: us-east-1
  credentialsSecretRef:
    namespace: crossplane-system
    name: aws-account-creds
    key: credentials

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: frezbo-vpc
spec:
  forProvider:
    cidrBlock: 10.16.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
      - key: Name
        value: frezbo-vpc
  reclaimPolicy: Delete
  providerConfigRef:
    name: aws-provider
```

**Comment by hasheddan** [comment]
@frezbo yep, I think what we are going to need to do here is add the `region` field to VPC. This unfortunately has the consequence of needing to `Get` the managed resource in the `Connect` method also. /cc @muvaf https://github.com/crossplane/provider-aws/blob/595a949c6485aff5a102e6cb8fecb3dbc6c160ea/pkg/clients/aws.go#L65

**Comment by frezbo** [comment]
@hasheddan I think we can also return the region here: https://github.com/crossplane/provider-aws/blob/595a949c6485aff5a102e6cb8fecb3dbc6c160ea/pkg/clients/aws.go#L111 if the region is present in the secret, WDYT?

**Comment by hasheddan** [comment]
@frezbo that is an interesting idea! However, the motivation here is decoupling the region from the credentials because that association really only exists at the SDK level. If we added to the `Secret` then it would functionally be the same as having it in the `ProviderConfig`.

**Comment by hasheddan** [comment]
@frezbo yep! And many of them already do. However, we need to make sure all resources do before next release 👍

**Comment by frezbo** [comment]
okay, great, I will start tinkering on this 👍

**Comment by hasheddan** [comment]
@frezbo awesome! Thanks so much 🙂

**Comment by frezbo** [comment]
Closing this as per discussion in the CrossPlane slack channel: https://crossplane.slack.com/archives/CEG3T90A1/p1599725730107300

**Pull request closed without merging**
