### PR TITLE
Build provider package with static content

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates the provider package image to only include a single static
package.yaml file that can be parsed by the package manager.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Draft until https://github.com/crossplane/crossplane/pull/1795 is merged, which is required for integration tests to pass. Integration tests will also have to be updated to support loading the package image into the cache dir due to the fact that the package manager will no longer be able to pull from local docker (for the package image, loading into kind will still work for provider controller). This process

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Integration tests demonstrate the functionality we are testing here, see https://github.com/crossplane/crossplane/pull/1807 for more info.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by muvaf** [comment]
https://github.com/crossplane/crossplane/pull/1795 is merged. I think we need this change to be able to install `master` provider-aws with `master` crossplane, right? I'm not getting any reactions from `master` Crossplane when I install provider-aws using `kind: Provider` right now.

**Comment by hasheddan** [comment]
@muvaf yes, this was waiting on https://github.com/crossplane/crossplane/pull/1807 which is now merged. I am updating accordingly 👍

**Comment by hasheddan** [comment]
@muvaf okay this is ready :)

**Comment by muvaf** [comment]
@hasheddan I'm getting the following on `Provider` object:
```
  Type     Reason                  Age               From                                 Message
  ----     ------                  ----              ----                                 -------
  Warning  InstallPackageRevision  1s (x4 over 17s)  packages/provider.pkg.crossplane.io  cannot create package revision: cannot create object: ProviderRevision.pkg.crossplane.io "provider-aws-crossplane/p" is invalid: metadata.name: Invalid value: "provider-aws-crossplane/p": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by hasheddan** [comment]
@muvaf did you supply `provider-aws-crossplane/p` as the `spec.package`? If so, this appears to be working as intended.

**Comment by muvaf** [comment]
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:muvaf
  packagePullPolicy: "Never"
```

That's what I created and the following is from api-server:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pkg.crossplane.io/v1alpha1","kind":"Provider","metadata":{"annotations":{},"name":"provider-aws"},"spec":{"package":"crossplane/provider-aws:muvaf","packagePullPolicy":"Never"}}
  creationTimestamp: "2020-10-07T12:11:09Z"
  generation: 1
  name: provider-aws
  resourceVersion: "4793"
  selfLink: /apis/pkg.crossplane.io/v1alpha1/providers/provider-aws
  uid: a1f43748-0895-4540-a894-3bcdef22f9ef
spec:
  package: crossplane/provider-aws:muvaf
  packagePullPolicy: Never
status:
  conditions:
  - lastTransitionTime: "2020-10-07T12:35:37Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentRevision: provider-aws-crossplane/p
```

**Comment by hasheddan** [comment]
@muvaf right, you cannot supply `crossplane/provider-aws:muvaf` as the `package` if your `packagePullPolicy: Never`. Please see https://github.com/crossplane/crossplane/pull/1807

**Comment by muvaf** [comment]
Oh, so `package` field expects another format if `packagePullPolicy: Never`?

**Comment by hasheddan** [comment]
@muvaf yes because if you say `packagePullPolicy: Never` then you are saying that you want to use the already cached package or fail. A cached package file could have `/` or `:` in the name. The value you supply for `package` must match exactly the package name in the cache, minus the `.xpkg` extension

**Comment by muvaf** [comment]
> A cached package file could have / or : in the name. The value you supply for package must match exactly the package name in the cache, minus the .xpkg extension

Oh that assumes I'm building with `crank`, right? Because `make build` gives me an image.

Anyway, I didn't want to deal with all that PVC stuff so I pushed the images as `muvaf/provider-aws:master` and `muvaf/provider-aws-controller:master` and the current status is:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pkg.crossplane.io/v1alpha1","kind":"Provider","metadata":{"annotations":{},"name":"provider-aws"},"spec":{"package":"muvaf/provider-aws:master"}}
  creationTimestamp: "2020-10-07T12:58:33Z"
  generation: 1
  name: provider-aws
  resourceVersion: "7296"
  selfLink: /apis/pkg.crossplane.io/v1alpha1/providers/provider-aws
  uid: ae41c5ee-11ef-4310-b8a7-7ca6f528fcc6
spec:
  package: muvaf/provider-aws:master
status:
  conditions:
  - lastTransitionTime: "2020-10-07T12:58:41Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  - lastTransitionTime: "2020-10-07T12:58:33Z"
    reason: UnhealthyPackageRevision
    status: "False"
    type: Healthy
  currentRevision: provider-aws-46fa5871417a

``` 
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ProviderRevision
metadata:
  creationTimestamp: "2020-10-07T12:58:37Z"
  finalizers:
  - revision.pkg.crossplane.io
  generation: 1
  labels:
    pkg.crossplane.io/package: provider-aws
  name: provider-aws-46fa5871417a
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1alpha1
    controller: true
    kind: Provider
    name: provider-aws
    uid: ae41c5ee-11ef-4310-b8a7-7ca6f528fcc6
  resourceVersion: "7293"
  selfLink: /apis/pkg.crossplane.io/v1alpha1/providerrevisions/provider-aws-46fa5871417a
  uid: 7a11e848-be48-4c90-bfac-42bdf7e09fe7
spec:
  desiredState: Active
  image: muvaf/provider-aws:master
  revision: 1
status:
  conditions:
  - lastTransitionTime: "2020-10-07T12:58:40Z"
    reason: UnhealthyPackageRevision
    status: "False"
    type: Healthy
  controllerRef:
    name: ""
```
```
Events:
  Type     Reason             Age                From                                         Message
  ----     ------             ----               ----                                         -------
  Warning  BindClusterRole    41s                rbac/providerrevision.pkg.crossplane.io      cannot apply ClusterRoleBinding: cannot create object: clusterrolebindings.rbac.authorization.k8s.io "crossplane:provider:provider-aws-46fa5871417a:system" already exists
  Normal   ApplyClusterRoles  38s (x3 over 41s)  rbac/providerrevision.pkg.crossplane.io      Applied RBAC ClusterRoles
  Normal   BindClusterRole    16s (x4 over 41s)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole to provider ServiceAccount(s)
  Warning  ParsePackage       6s (x3 over 38s)   packages/providerrevision.pkg.crossplane.io  cannot parse package contents: Object 'Kind' is missing in '# Human readable title of application.
title: AWS Provider

overviewShort: The AWS Crossplane provider enables infrastructure management for Amazon Web Services.
overview: |-
 The Amazon Web Services Crossplane provider adds support for managing AWS resources in Kubernetes.

# Markdown description of this entry
readme: |
 This `provider-aws` repository is a Crossplane infrastructure provider for [Amazon Web Services (AWS)](https://aws.amazon.com).
 The provider that is built from the source code in this repository can be installed into a Crossplane control plane and adds the following new functionality:

 * Custom Resource Definitions (CRDs) that model AWS infrastructure and services (e.g. [Amazon Relational Database Service (RDS)](https://aws.amazon.com/rds/), [EKS clusters](https://aws.amazon.com/eks/), etc.)
 * Controllers to provision these resources in AWS based on the users desired state captured in CRDs they create
 * Implementations of Crossplane's portable resource abstractions, enabling AWS resources to fulfill a user's general need for cloud services

# Maintainer names and emails.
maintainers:
- name: Jared Watts
  email: jared@upbound.io

# Owner names and emails.
owners:
- name: Jared Watts
  email: jared@upbound.io

# Human readable company name
company: Crossplane

# Primary category describing this package
category: Infrastructure

# Type of package: Provider, Stack, or Application
packageType: Provider

# Keywords that describe this application and help search indexing
keywords:
- "amazon"
- "aws"
- "infrastructure"

# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane.io"
source: "https://github.com/crossplane/provider-aws"

# RBAC ClusterRoles will be generated permitting this package to use all verbs on all
# resources in the groups listed below.
permissionScope: Cluster
dependsOn:
- crd: '*.cache.crossplane.io/v1alpha1'
- crd: '*.compute.crossplane.io/v1alpha1'
- crd: '*.database.crossplane.io/v1alpha1'
- crd: '*.core.crossplane.io/v1alpha1'
- crd: '*.storage.crossplane.io/v1alpha1'
- crd: '*.workload.crossplane.io/v1alpha1'

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0

'
```

**Comment by hasheddan** [comment]
> Oh that assumes I'm building with crank, right? Because make build gives me an image

@muvaf please look at what the integration tests are doing here. The image is being build with `Docker`, then it is being saved to an `xpkg` tarball (https://github.com/crossplane/provider-aws/pull/365/files#diff-af11792cb54bfa8609d137ea432ab051R178). Also, it is clear that you are using an old version of `provider-aws` (there is not README content in the new one).

**Comment by hasheddan** [comment]
@negz could you give this a quick look? I will follow with updates to the other providers :+1:

**Review by negz — APPROVED** [review]

**Comment by hasheddan** [comment]
xref https://github.com/crossplane/crossplane/issues/1756

**Pull request merged**
