### PR TITLE
Rename OriginSSLProtocols to OriginSslProtocols for distributions

### LINKED ISSUE #894: CloudFront Distribution Custom Origin Reconciling Loop
### What happened?

Deploying a cloudfront distribution with a custom origin causes the provider-aws to enter an infinite loop of 

```
2021-10-27T21:22:52.190Z	DEBUG	provider-aws	Successfully requested update of external resource	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution", "uid": "65ef1e28-17dd-48db-a8ae-643fd09f64b2", "version": "53118503", "external-name": "E36PA3AGLMFTIU", "requeue-after": "2021-10-27T21:23:52.190Z"}
2021-10-27T21:22:52.190Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Distribution","name":"broadcast-754467cb5b-s999r-distribution","uid":"65ef1e28-17dd-48db-a8ae-643fd09f64b2","apiVersion":"cloudfront.aws.crossplane.io/v1alpha1","resourceVersion":"53118503"}, "reason": "UpdatedExternalResource", "message": "Successfully requested update of external resource"}
2021-10-27T21:22:52.207Z	DEBUG	provider-aws	Reconciling	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution"}
2021-10-27T21:22:52.792Z	DEBUG	provider-aws	Successfully requested update of external resource	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution", "uid": "65ef1e28-17dd-48db-a8ae-643fd09f64b2", "version": "53118503", "external-name": "E36PA3AGLMFTIU", "requeue-after": "2021-10-27T21:23:52.792Z"}
2021-10-27T21:22:52.792Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Distribution","name":"broadcast-754467cb5b-s999r-distribution","uid":"65ef1e28-17dd-48db-a8ae-643fd09f64b2","apiVersion":"cloudfront.aws.crossplane.io/v1alpha1","resourceVersion":"53118503"}, "reason": "UpdatedExternalResource", "message": "Successfully requested update of external resource"}
2021-10-27T21:22:52.804Z	ERROR	controller-runtime.manager.controller.managed/distribution.cloudfront.aws.crossplane.io	Reconciler error	{"reconciler group": "cloudfront.aws.crossplane.io", "reconciler kind": "Distribution", "name": "broadcast-754467cb5b-s999r-distribution", "namespace": "", "error": "cannot update managed resource status: Operation cannot be fulfilled on distributions.cloudfront.aws.crossplane.io \"broadcast-754467cb5b-s999r-distribution\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214
2021-10-27T21:22:52.804Z	DEBUG	provider-aws	Reconciling	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution"}
```

### How can we reproduce it?

Deploy a distribution with a custom origin

```
# Distribution will not be deleted unless you mark the distribution disabled via
# spec.distributionConfig.enabled.
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: example2-distribution
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      origins:
        items:
          - domainName: exampledomain.example.com
            id: example
            originPath: "/helloworld"
            customHeaders:
              items:
                - headerName: "test"
                  headerValue: "test"
              quantity: 1
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "http-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1
                quantity: 1
      defaultCacheBehavior:
        targetOriginID: example
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
  providerConfigRef:
    name: aws-provider
```

### What environment did it happen in?
Crossplane version: crossplane-1.4.1

### PR DESCRIPTION
**Pull request by gstramandinoli**
### Description of your changes

Original ticket of issue here https://github.com/crossplane/provider-aws/issues/894

Creating a distribution with a custom origin was stuck infinitely reconciling every second. After looking into this, it was due to a naming difference between provider-aws and the aws sdk where for provider-aws the variable was OriginSSLProtocols and for aws-sdk it was OriginSslProtocols. 

Thus, while copying unset values in the responseObject to the crObject (https://github.com/crossplane/provider-aws/blob/master/pkg/controller/cloudfront/lateinit.go#L173) it would skip over the OriginSSLProtocols since the FieldByName function used here (https://github.com/crossplane/provider-aws/blob/master/pkg/controller/cloudfront/lateinit.go#L217) is case-sensitive. I updated the variables to match case. 

#### Rename OriginSSLProtocols to OriginSslProtocols to match AWS SDK

Fixes #894 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

I built the image with the changes. The image is available here (gstramandinoli/provider-aws:debugv35). I deployed the provider-aws. I deployed a distribution with a custom origin. I monitored the logs and saw that it was not reconciling infinitely anymore. In AWS console I saw that the distribution was successfully deployed. I modified the distribution and changed a parameter. I checked teh provider logs again and saw that it successfully updated the distribution. I checked in AWS console that it also updated there. I then disabled the distribution and cross checked again that the changes were reflected. I then deleted and cross checked that the changes were reflected. 

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
@gstramandinoli can you add DCO ?

**Comment by muvaf** [comment]
Hi @gstramandinoli ! Thanks for the PR! The files prefixed with `zz_` are generated by the ACK code generator, so if you made changes to those files manually then they won't survive a `make reviewable`. I wonder why our tests in GH actions didn't run to catch it.

@ulucinar would you mind taking a look at this issue since it's related to reflect-based late-initializer behavior?

**Comment by stevendborrelli** [comment]
@ulucinar I have an attempted fix in #922.

**Comment by haarchri** [comment]
@gstramandinoli  thanks for your work - it is now fixed and merged via #922

**Pull request closed without merging**
